name: Sync to Medaminer Repo

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repository
        uses: actions/checkout@v3
        with:
          repository: medamineriahi2023/official-repo
          token: ${{ secrets.MEDAMINERIAHI2023_PAT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "medaminer"
          git config user.email "medaminer@gmail.com"

      - name: Add Medaminer repository as remote
        run: |
          git remote add destination https://x-access-token:${{ secrets.MEDAMINER_PAT }}@github.com/medaminer/official-repo.git

      - name: Authenticate as Medaminer
        env:
          GIT_AUTHOR_NAME: medaminer
          GIT_AUTHOR_EMAIL: medaminer@gmail.com
          GIT_COMMITTER_NAME: medaminer
          GIT_COMMITTER_EMAIL: medaminer@gmail.com
        run: |
          git fetch destination
          git rebase destination/main

      - name: Push changes to Medaminer repository
        run: |
          git push destination main --force
          git push destination --tags --force
