name: Sync to Medaminer Repo

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository (medamineriahi2023)
        uses: actions/checkout@v3
        with:
          repository: medamineriahi2023/official-repo
          token: ${{ secrets.MEDAMINERIAHI2023_PAT }}
          fetch-depth: 0

      - name: Configure Git author info as medaminer
        run: |
          git config user.name "medaminer"
          git config user.email "medaminer@gmail.com"

      - name: Add destination remote (medaminer)
        run: |
          git remote add destination https://x-access-token:${{ secrets.YASSIN_PAT }}@github.com/medaminer/official-repo.git

      - name: Show Git remotes for debugging
        run: git remote -v

      - name: Fetch all branches from origin
        run: git fetch origin --prune

      - name: Push all branches and tags to destination
        run: |
          git push destination --all --force
          git push destination --tags --force
