name: Mirror to Medaminer's Repository

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "medaminer"
          git config user.email "medaminer@gmail.com"

      - name: Add Medaminer's repository as remote
        run: |
          git remote add origin https://x-access-token:${{ secrets.YASSIN_PAT }}@github.com/medaminer/official-repo.git

      - name: Push changes to Medaminer's repository
        run: |
          git push origin --all
          git push origin --tags
